// @version 1.0.0
// v1.0.0 (ADR-0081 / T-20260918-002): shared-file taxonomy and conflict-state
// parsing for dev-sync's main-drift pre-flight and --conclude-merge modes.
// Import-safe (pure functions, no git I/O, no pipeline side effects) — the
// pipeline itself is not import-safe, so tests target this module.
//   - SHARED_PIPELINE_FILES: the CONSTITUTION §3.3 shared pipeline file set —
//     dev-sync regenerates these on every commit, so parallel unmerged
//     branches conflict here by default.
//   - sharedPipelineFilesChanged(changedOnMain): intersection of a changed-file
//     list with the shared set (normalizes Windows separators).
//   - parseUnresolvedConflicts(gitOutput): parses
//     `git diff --name-only --diff-filter=U` output into a trimmed, non-empty
//     path list (the --conclude-merge pre-commit check).

/**
 * CONSTITUTION §3.3 shared pipeline files — regenerated by dev-sync on every
 * commit regardless of workstream, so parallel unmerged branches conflict on
 * these by default, not by exception.
 */
export const SHARED_PIPELINE_FILES: readonly string[] = [
    'CHANGELOG.md',
    'memory/MEMORY.md',
    'docs/VERSION_MANIFEST.md',
    'scripts/README.md',
    'templates/common/scripts/README.md',
];

/**
 * Filter a changed-file list (e.g. `git diff --name-only <base> origin/main`
 * output split into lines) down to the CONSTITUTION §3.3 shared pipeline files.
 * Windows separators are normalized before matching.
 */
export function sharedPipelineFilesChanged(changedOnMain: string[]): string[] {
    const set = new Set(changedOnMain.map((f) => f.replaceAll('\\', '/')));
    return SHARED_PIPELINE_FILES.filter((f) => set.has(f));
}

/**
 * Parse `git diff --name-only --diff-filter=U` output into the unresolved
 * conflict paths. Empty/whitespace lines are dropped; order is preserved.
 */
export function parseUnresolvedConflicts(gitOutput: string): string[] {
    return gitOutput
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean);
}
