"use client";
import { useState } from "react";
import { addMember, changeMemberRole, changeMemberStatus, issueTemporaryPassword } from "../app/actions/admin";

type Member = { id: string; email: string | null; role: "ADMIN" | "USER"; status: "ACTIVE" | "INACTIVE"; lastLoginAt: string | null; createdAt: string };
export function GrantForm() {
  const [email, setEmail] = useState(""); const [role, setRole] = useState<"USER" | "ADMIN">("USER"); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  return <form className="card inline-form" onSubmit={async (event) => { event.preventDefault(); setPending(true); const result = await addMember({ email, role }); setPending(false); if (!result.ok) { setMessage(result.error.message); return; } setEmail(""); setMessage(`계정을 만들었습니다. 임시 비밀번호: ${result.data.temporaryPassword} — 지금 복사해 전달하세요. 다시 볼 수 없습니다.`); }}><div><h2>팀원 초대</h2><p className="muted">임시 비밀번호는 한 번만 표시됩니다. 팀원은 첫 로그인에서 새 비밀번호를 정합니다.</p></div><label>이메일<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>역할<select value={role} onChange={(event) => setRole(event.target.value as "USER" | "ADMIN")}><option value="USER">사용자</option><option value="ADMIN">관리자</option></select></label><button className="button primary" disabled={pending}>{pending ? "계정 생성 중…" : "계정 만들기"}</button>{message && <p role="status" className="row-message">{message}</p>}</form>;
}
export function GrantRow({ grant }: { grant: Member }) {
  const [role, setRole] = useState(grant.role); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  async function run(action: () => Promise<{ ok: boolean; data?: unknown; error?: { message: string } }>) { setPending(true); const result = await action(); setPending(false); const password = typeof result.data === "object" && result.data && "temporaryPassword" in result.data ? String((result.data as { temporaryPassword: string }).temporaryPassword) : ""; setMessage(result.ok ? password ? `새 임시 비밀번호: ${password} — 지금 복사해 전달하세요.` : "저장했습니다." : result.error?.message ?? "처리하지 못했습니다."); }
  return <article className="grant-row" aria-busy={pending}><div><strong>{grant.email ?? "기존 계정 (이메일 설정 필요)"}</strong><small>{grant.lastLoginAt ? `마지막 로그인 ${new Date(grant.lastLoginAt).toLocaleString("ko-KR")}` : "로그인 기록 없음"}</small></div><select aria-label={`${grant.email ?? "계정"} 역할`} value={role} onChange={(event) => setRole(event.target.value as "USER" | "ADMIN")}><option value="USER">사용자</option><option value="ADMIN">관리자</option></select><span className={`status-badge status-${grant.status.toLowerCase()}`}>{grant.status === "ACTIVE" ? "활성" : "비활성"}</span><button className="button secondary" type="button" onClick={() => void run(() => changeMemberRole(grant.id, role))}>역할 저장</button><button className="button text" type="button" onClick={() => void run(() => issueTemporaryPassword(grant.id))}>임시 비밀번호 재발급</button><button className="button text" type="button" onClick={() => void run(() => changeMemberStatus(grant.id, grant.status === "ACTIVE" ? "INACTIVE" : "ACTIVE"))}>{grant.status === "ACTIVE" ? "비활성화" : "다시 활성화"}</button>{message && <small role="status" className="row-message">{message}</small>}</article>;
}
