"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { createDeployment } from "../app/actions/deployments";

type Repository = { id: string; name: string; fullName: string; ownerLogin: string; private: boolean; defaultBranch: string; description: string | null };
type Branch = { name: string; sha?: string; protected?: boolean };

export function DeploymentForm() {
  const router = useRouter(); const [repositories, setRepositories] = useState<Repository[]>([]); const [repository, setRepository] = useState(""); const [branch, setBranch] = useState(""); const [branches, setBranches] = useState<Branch[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [needsReconnect, setNeedsReconnect] = useState(false); const errorRef = useRef<HTMLDivElement>(null);
  useEffect(() => { void (async () => { try { const result = await fetch("/api/github/repositories", { cache: "no-store" }); const body = await result.json() as { repositories?: Repository[]; message?: string; error?: string }; if (!result.ok) { if (result.status === 401 || body.error === "GITHUB_REAUTH_REQUIRED") setNeedsReconnect(true); throw new Error(body.message); } setRepositories(body.repositories ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : "GitHub 저장소를 불러오지 못했습니다."); } finally { setLoading(false); } })(); }, []);
  async function choose(value: string) { setRepository(value); setBranches([]); const selected = repositories.find((item) => item.fullName === value); if (!selected) return; setBranch(selected.defaultBranch); try { const result = await fetch(`/api/github/repositories/${encodeURIComponent(selected.ownerLogin)}/${encodeURIComponent(selected.name)}/branches`, { cache: "no-store" }); const body = await result.json() as { branches?: Branch[]; message?: string }; if (!result.ok) throw new Error(body.message); setBranches(body.branches ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : "버전 목록을 불러오지 못했습니다."); } }
  async function submit(event: React.FormEvent) { event.preventDefault(); setPending(true); setMessage(""); const result = await createDeployment({ repository, branch, idempotencyKey: crypto.randomUUID() }); setPending(false); if (!result.ok) { setMessage(result.error.message); queueMicrotask(() => errorRef.current?.focus()); return; } router.push(`/deployments/${result.data.id}`); }
  const visible = repositories.filter((item) => `${item.fullName} ${item.description ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  return <form className="card form-card" onSubmit={submit} aria-busy={pending}><div><p className="eyebrow">3단계 배포</p><h2>저장소를 골라 배포하세요</h2><p className="muted">포트와 빌드 방식은 저장소를 보고 자동으로 결정합니다.</p></div>{message && <div ref={errorRef} role="alert" tabIndex={-1} className="alert error"><p>{message}</p>{needsReconnect && <a className="button secondary" href="/api/github/connect">GitHub 다시 연결</a>}</div>}<label>1. 저장소 검색<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="저장소 이름으로 검색" disabled={loading} /></label><label>저장소<select required value={repository} onChange={(event) => void choose(event.target.value)} disabled={loading}><option value="">{loading ? "저장소를 불러오는 중…" : "저장소를 선택하세요"}</option>{visible.map((item) => <option key={item.id} value={item.fullName}>{item.fullName}{item.private ? " · 비공개" : ""}</option>)}</select></label><label>2. 버전<select required value={branch} onChange={(event) => setBranch(event.target.value)} disabled={!repository}><option value="">버전을 선택하세요</option>{(branches.length ? branches : branch ? [{ name: branch }] : []).map((item) => <option key={item.name} value={item.name}>{item.name}{item.name === repositories.find((entry) => entry.fullName === repository)?.defaultBranch ? " · 기본" : ""}</option>)}</select><small className="muted">기본 브랜치가 먼저 선택됩니다. 필요할 때만 다른 버전을 고르세요.</small></label><button className="button primary" disabled={pending || !repository || !branch}>{pending ? "배포를 준비하는 중…" : "3. 배포 시작"}</button></form>;
}
