import Link from "next/link";
import { redirect } from "next/navigation";
import { prisma } from "../../lib/db";
import { getCurrentUser } from "../../lib/auth/current-user";
import { AppShell } from "../../components/app-shell";
import { DeploymentForm } from "../../components/deployment-form";
import { StatusBadge } from "../../components/status-badge";
import { GitHubConnection } from "../../components/github-connection";
export const dynamic = "force-dynamic";
export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ github?: string }> }) { const user = await getCurrentUser(); if (!user) redirect("/login"); if (user.mustChangePassword) redirect("/account/change-password"); const params = await searchParams; const notice = ["connected", "failed", "conflict"].includes(params.github ?? "") ? params.github as "connected" | "failed" | "conflict" : undefined; const deployments = await prisma.deployment.findMany({ where: user.role === "ADMIN" ? {} : { userId: user.id }, orderBy: { updatedAt: "desc" }, take: 20 }); return <AppShell user={user}><header className="page-header"><div><p className="eyebrow">작업 공간</p><h1>배포하기</h1><p className="muted">저장소와 버전을 고르면 나머지는 자동으로 준비합니다.</p></div></header><GitHubConnection login={user.githubLogin} notice={notice} />{user.githubLogin && <DeploymentForm />}<section className="card" aria-labelledby="recent-deployments-heading"><h2 id="recent-deployments-heading">최근 배포</h2>{deployments.length === 0 ? <p className="empty">아직 배포가 없습니다. 첫 번째 서비스를 공개해 보세요.</p> : <div className="deployment-list">{deployments.map((deployment) => <Link className="deployment-row" href={`/deployments/${deployment.id}`} key={deployment.id} aria-label={`${deployment.actualName ?? deployment.requestedName} 배포 보기`}><StatusBadge status={deployment.status} /><span><strong>{deployment.actualName ?? deployment.requestedName}</strong><small>{deployment.repository} · {deployment.branch}</small></span><time dateTime={deployment.updatedAt.toISOString()}>{deployment.updatedAt.toLocaleString("ko-KR")}</time><span aria-hidden="true">→</span></Link>)}</div>}</section></AppShell>; }
